### ISSUE TITLE
とりあえず動かす用のキャラクター的な画像

### ISSUE THREAD

**Issue by hana69** [mtlilium/RANDOM_reunion#1]
クォータービューで４方向どちらを向いているか分かるような画像。サイズは本番のキャラクターと同じ

基本:~2018/12/11
最終:~2018/12/13

**Comment by sugichan0116** [comment]
![girl](https://raw.githubusercontent.com/sugichan0116/ProjectDesign/master/dot/girl.png)
とりあえずできたが、どうすればいい？

**Comment by hana69** [comment]
普通にこのまま使えそうなのでOKっぽい
